version: '3.8'

services:
  typeorm-mysql:
    container_name: typeorm-mysql
    image: 'mysql:5.7.29'
    platform: linux/amd64
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: rootpw
      MYSQL_DATABASE: app-db
      MYSQL_USER: admin
      MYSQL_PASSWORD: adminpw
